In [1]:
import numpy as np
import pandas as pd

In [2]:
x=np.arange(10)
x = np.tile(x,(5,1))
print(x)

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]


In [3]:
np.apply_along_axis(np.random.permutation, 1, x)

array([[0, 6, 3, 9, 8, 5, 4, 7, 2, 1],
       [6, 1, 3, 0, 4, 9, 2, 7, 8, 5],
       [4, 2, 5, 1, 8, 7, 9, 6, 3, 0],
       [1, 5, 0, 6, 7, 9, 2, 3, 8, 4],
       [7, 2, 6, 0, 4, 8, 3, 5, 9, 1]])